name: go-release
description: Build static-linked Go executables for the module in GITHUB_WORKSPACE
inputs:
  github-token:
    description: Value of GITHUB_TOKEN or equivalent API token
    required: true
outputs: {}
runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}